//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T_GuideMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string ClassName { get; set; }
        public int classId { get; set; }
        public string TeacherName { get; set; }
        public Nullable<int> TakenState { get; set; }
        public Nullable<System.DateTime> Tme { get; set; }
    }
}
